self-hosted-runner:
  labels:
    - warp-macos-latest-arm64-6x
    - blacksmith-6vcpu-macos-15
    - blacksmith-6vcpu-macos-26
    - blacksmith-6vcpu-macos-latest
    - blacksmith-12vcpu-macos-15
    - blacksmith-12vcpu-macos-26
    - blacksmith-12vcpu-macos-latest
